# Generated by Django 5.1.2 on 2024-11-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='id_cliente',
            field=models.PositiveSmallIntegerField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
