# Generated by Django 5.1 on 2024-11-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.PositiveSmallIntegerField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('direccion', models.PositiveBigIntegerField(max_length=10)),
                ('telefono', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('puesto', models.CharField(max_length=50)),
            ],
        ),
    ]
