# Generated by Django 5.1.2 on 2024-11-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado_app', '0002_alter_empleado_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.PositiveSmallIntegerField(max_length=10),
        ),
    ]
