# Generated by Django 5.1.2 on 2024-11-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.PositiveSmallIntegerField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.PositiveBigIntegerField(max_length=10)),
                ('correo', models.CharField(max_length=100)),
                ('tipo_de_producto', models.CharField(max_length=50)),
                ('tipo_de_entrega', models.CharField(max_length=50)),
            ],
        ),
    ]
