# Generated by Django 5.1 on 2024-11-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursal_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='horario',
            field=models.CharField(max_length=50),
        ),
    ]
