# Generated by Django 5.1.2 on 2024-11-19 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursal_app', '0002_alter_sucursal_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='horario',
            field=models.TimeField(),
        ),
    ]
