# Generated by Django 5.1.2 on 2024-11-19 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursal_app', '0003_alter_sucursal_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='horario',
            field=models.CharField(max_length=20),
        ),
    ]
